# Cloudflare Pages configuration
name = "recipe-ai4"
compatibility_date = "2023-11-21"
pages_build_output_dir = ".next"

# Production environment
[env.production]
NODE_VERSION = "20"

[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://recipegeniefree.com"
NEXT_TELEMETRY_DISABLED = "1"

# Preview environment
[env.preview]
NODE_VERSION = "20"

[env.preview.vars]
NEXT_TELEMETRY_DISABLED = "1" 