# Cloudflare Pages configuration
name = "recipe-sage"
compatibility_date = "2023-11-21"
pages_build_output_dir = ".next"

# Node.js version
[env.production]
NODE_VERSION = "20"

# Environment variables
[vars]
NEXT_PUBLIC_APP_URL = "https://recipe-sage.pages.dev"
NEXT_TELEMETRY_DISABLED = "1" 