import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-gray-50 pb-20">
      {/* Header */}
      <header className="bg-gradient-to-r from-red-500 to-red-600 py-8 md:py-12 mb-8 md:mb-16">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-center mb-0">
            <span className="text-4xl mr-3">🍳</span>
            <h1 className="text-3xl md:text-4xl font-bold text-white">Terms of Service</h1>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white p-8 rounded-lg shadow-md">
          <div className="prose max-w-none">
            <h2>Terms of Service for Recipe Generator</h2>
            <p><em>Last Updated: {new Date().toLocaleDateString()}</em></p>
            
            <p>Welcome to Recipe Generator! Please read these Terms of Service ("Terms") carefully as they contain important information about your legal rights, remedies, and obligations. By accessing or using Recipe Generator, you agree to comply with and be bound by these Terms.</p>
            
            <h3>1. Acceptance of Terms</h3>
            <p>By accessing or using our website, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, please do not use our services.</p>
            
            <h3>2. Description of Service</h3>
            <p>Recipe Generator provides an online platform that uses artificial intelligence to generate recipes based on user inputs such as ingredients or recipe names. Our service is provided "as is" and "as available" without warranties of any kind.</p>
            
            <h3>3. AI-Generated Content Disclaimer</h3>
            <p>The recipes generated by our platform are created using artificial intelligence technology. While we strive to provide accurate and useful recipes, we make no representations or warranties about the accuracy, completeness, reliability, or safety of any recipes generated. Users should exercise their own judgment when following any recipe, particularly regarding:</p>
            <ul>
              <li>Food allergies and dietary restrictions</li>
              <li>Cooking techniques and food safety</li>
              <li>Ingredient substitutions and measurements</li>
              <li>Cooking times and temperatures</li>
            </ul>
            
            <h3>4. User Conduct</h3>
            <p>When using our service, you agree not to:</p>
            <ul>
              <li>Use the service for any illegal purpose</li>
              <li>Attempt to access, scrape, or otherwise interfere with our platform's functionality</li>
              <li>Use our service to generate content that is harmful, offensive, or violates the rights of others</li>
              <li>Share or redistribute AI-generated recipes without appropriate attribution to Recipe Generator</li>
              <li>Attempt to circumvent any security features of our website</li>
            </ul>
            
            <h3>5. Intellectual Property</h3>
            <p>The content, organization, graphics, design, and other matters related to the Recipe Generator website are protected under applicable copyrights and other proprietary laws. The copying, redistribution, use, or publication by you of any such content or any part of the Service is prohibited without express written permission.</p>
            
            <h3>6. User-Generated Content</h3>
            <p>If our service allows users to save or share recipes, you retain ownership of your content, but grant us a non-exclusive, royalty-free license to use, store, and display that content in connection with our service.</p>
            
            <h3>7. Limitation of Liability</h3>
            <p>In no event shall Recipe Generator, its operators, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.</p>
            
            <h3>8. Changes to Terms</h3>
            <p>We reserve the right to modify these Terms at any time. We will provide notice of any significant changes by posting the updated Terms on our website with a new effective date. Your continued use of our service after such changes constitutes your acceptance of the new Terms.</p>
            
            <h3>9. Governing Law</h3>
            <p>These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Recipe Generator operates, without regard to its conflict of law provisions.</p>
            
            <h3>10. Contact Information</h3>
            <p>If you have any questions about these Terms, please contact us at:</p>
            <p>Email: info@recipegenerator.com</p>
          </div>
          
          <div className="mt-8 text-center">
            <Link href="/index.html" className="inline-flex items-center text-red-500 hover:text-red-700 font-medium">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5 mr-2"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fillRule="evenodd"
                  d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z"
                  clipRule="evenodd"
                />
              </svg>
              Return to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
} 