import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-gray-50 pb-20">
      {/* Header */}
      <header className="bg-gradient-to-r from-red-500 to-red-600 py-8 md:py-12 mb-8 md:mb-16">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-center mb-0">
            <span className="text-4xl mr-3">🍳</span>
            <h1 className="text-3xl md:text-4xl font-bold text-white">Privacy Policy</h1>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 max-w-4xl">
        <div className="bg-white p-8 rounded-lg shadow-md">
          <div className="prose max-w-none">
            <h2>Privacy Policy for Recipe Generator</h2>
            <p><em>Last Updated: {new Date().toLocaleDateString()}</em></p>
            
            <p>At Recipe Generator, we value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your information when you visit our website.</p>
            
            <h3>Information We Collect</h3>
            <p>When you use our Recipe Generator, we may collect the following types of information:</p>
            <ul>
              <li><strong>Usage Information:</strong> We collect information about your interactions with our website, including the recipes you generate, search queries, and how you use our features.</li>
              <li><strong>Device Information:</strong> We automatically collect device information such as your IP address, browser type, operating system, and device identifiers.</li>
              <li><strong>Cookies and Similar Technologies:</strong> We use cookies and similar technologies to enhance your experience, analyze usage patterns, and tailor content to your interests.</li>
            </ul>
            
            <h3>How We Use Your Information</h3>
            <p>We use the information we collect for various purposes, including:</p>
            <ul>
              <li>Providing and improving our recipe generation service</li>
              <li>Personalizing your experience</li>
              <li>Analyzing usage patterns to optimize our website</li>
              <li>Responding to your requests or inquiries</li>
              <li>Displaying relevant advertisements (if applicable)</li>
            </ul>
            
            <h3>AI-Generated Content</h3>
            <p>Our Recipe Generator uses artificial intelligence to create recipe content. While we strive to provide accurate and useful recipes, please note that all recipes are generated by AI and should be used with appropriate caution. We recommend reviewing ingredients, cooking times, and techniques to ensure they align with food safety standards and your dietary needs.</p>
            
            <h3>Third-Party Services</h3>
            <p>We may use third-party services that collect information about you when you visit our website. These services may include:</p>
            <ul>
              <li>Google Analytics for website usage analysis</li>
              <li>Google AdSense for displaying advertisements</li>
              <li>AI service providers for recipe generation</li>
            </ul>
            
            <h3>Your Choices</h3>
            <p>You can manage your privacy preferences in several ways:</p>
            <ul>
              <li>Browser Settings: You can set your browser to refuse cookies or alert you when cookies are being sent.</li>
              <li>Do Not Track: We honor Do Not Track signals from your browser when technically feasible.</li>
              <li>Opt-Out: You can opt out of certain data collection by contacting us.</li>
            </ul>
            
            <h3>Data Security</h3>
            <p>We implement appropriate security measures to protect your personal information. However, no method of transmission over the Internet or method of electronic storage is 100% secure.</p>
            
            <h3>Children's Privacy</h3>
            <p>Our website is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13.</p>
            
            <h3>Changes to This Privacy Policy</h3>
            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.</p>
            
            <h3>Contact Us</h3>
            <p>If you have any questions about this Privacy Policy, please contact us at:</p>
            <p>Email: info@recipegenerator.com</p>
          </div>
          
          <div className="mt-8 text-center">
            <Link href="/" className="inline-flex items-center text-red-500 hover:text-red-700 font-medium">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5 mr-2"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fillRule="evenodd"
                  d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z"
                  clipRule="evenodd"
                />
              </svg>
              Return to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
} 